spring:
  application:
    name: company-service

  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

