server:
  port: ${COMPANY_SERVICE_PORT:8082}

spring:
  application:
    name: company-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
  datasource:
    url: jdbc:postgresql://${COMPANY_DB_HOST:localhost}:${COMPANY_DB_PORT:5433}/${COMPANY_DB_DBNAME:company_db}
    username: ${COMPANY_DB_USERNAME:user}
    password: ${COMPANY_DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.web: DEBUG
      feign: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

