server:
  port: ${USER_SERVICE_PORT:8081}

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:" # Автоматически ищет Config Server через Discovery
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
  datasource:
    url: jdbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5432}/${USER_DB_DBNAME:user_db}
    username: ${USER_DB_USERNAME:user}
    password: ${USER_DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.web: DEBUG
      feign: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true