spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:" # Автоматически ищет Config Server через Discovery
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true