server:
    port: ${EUREKA_PORT:8761}

spring:
    application:
        name: eureka-server

eureka:
    instance:
        hostname: ${EUREKA_HOST:localhost}
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/