server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/company_db
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
