server:
  port: ${CONFIG_PORT:8888}

spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
